### ISSUE TITLE
Add migration path demonstration for existing tables

### ISSUE THREAD

**Issue by Istanful** [derrickreimer/sequenced#32]
# Add migration path demonstration for existing application
I just imported this gem to an existing application. I wanted to add an `article_number` column to my `offers` that is scoped to their respective organization.

In order to add the `article_number` column with a not null constraint, I had to create a migration with some custom SQL. 
```ruby
# Add the column without a constraint
add_column :offers, :article_number, :integer

# Generate the supposed values
execute <<~SQL
    UPDATE offers AS affected_offers
    SET article_number = (
      SELECT COUNT(id)
      FROM offers
      WHERE offers.organization_id = affected_offers.organization_id
      AND offers.id < affected_offers.id
    ) + 1
SQL

# Add not null constraint
change_column :offers, :article_number, :integer, null: false

# Add index
add_index :offers, %i[article_number organization_id], unique: true
```

How about adding an example for this in the README? Or even better create a generator?
If you think it's reasonable I could open a PR. :)

**Comment by derrickreimer** [comment]
Sure, I think it makes sense to drop a little example in the README. I'm less inclined to go the generator route, since this will likely involve a careful multi-stage deploy/migration flow for production applications. Less magic is better here.

I'd recommend using `ROW_NUMBER()` function: https://stackoverflow.com/questions/41069860/sql-update-records-with-row-number

**Comment by Istanful** [comment]
Neat. I did not know about this one. :)

I've opened a pull request here: #33
